pipeline:
    stages:
        - stage:
              variables:
                  - name: MAVEN_IMAGE
                    type: String
                    value: maven:3.8.4-openjdk-17
              type: CI
              spec:
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-builds
                  execution:
                      steps:
                          - step:
                                type: RestoreCacheS3
                                spec:
                                    region: eu-west-2
                                    key: sonar
                                    connectorRef: org.AWS
                                    bucket: mansong-maven
                                    archiveFormat: Gzip
                                name: Restore Maven Cache
                                identifier: Restore_Maven_Cache
                          - step:
                                type: RunTests
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: <+build.variables.MAVEN_IMAGE>
                                    language: Java
                                    buildTool: Maven
                                    args: test
                                    runOnlySelectedTests: true
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - "**/*.xml"
                                    resources:
                                        limits:
                                            memory: 4Gi
                                            cpu: "2.0"
                                name: Run Tests
                                identifier: Run_TI
                          - step:
                                template:
                                    versionLabel: v1.0.0
                                    templateRef: check_licence_compliance
                                name: Check Licence Compliance
                                identifier: Check_Licence_Compliance
                          - step:
                                template:
                                    versionLabel: v1.0.0
                                    templateRef: cleanup_maven_repository
                                name: Clean Up Maven Repo
                                identifier: Clean_Up_Maven_Repo
                          - step:
                                type: Run
                                spec:
                                    image: bash:latest
                                    connectorRef: org.Dockerhub
                                    command: ls -larth
                                name: echo
                                identifier: echo
                          - step:
                                type: SaveCacheS3
                                spec:
                                    sourcePaths:
                                        - /harness/.m2/repository
                                    region: eu-west-1
                                    override: true
                                    key: sonar
                                    connectorRef: org.AWS
                                    bucket: mansong-maven
                                    archiveFormat: Gzip
                                name: Save Maven Cache
                                identifier: Save_Maven_Cache
                  cloneCodebase: true
              name: build
              identifier: build
    properties:
        ci:
            codebase:
                repoName: sonar-java
                connectorRef: org.Github
                build: <+input>
    projectIdentifier: Sonar
    orgIdentifier: default
    name: sonar-java
    identifier: sonarjava
